### ISSUE TITLE
Sitemap.xml not created in case of multilingual website.

### ISSUE THREAD

**Issue by daljitkaur9** [callumbwhyte/friendly-sitemap#11]
Hello,
I am using umbraco 8.8.
I have installed the package from NuGet and everything went smooth for the default language.
e.g http://www.example.com/sitemap.xl --> gave me the sitemap file for the english (default) site.
But i am using same domain for , let's say, swedish site. e.g http://www.example.com/sv-se 
So when i tried to access sitemap.xml from this url https://www.example.com/sv-se/sitemap.xml --> It gives me 404 error.
Am i missing somethig.
Kindly help.

**Comment by callumbwhyte** [comment]
Hey @daljitkaur9,

Thanks for using Friendly Sitemap!

This is a known issue, and something I'd like to fix.

The issue lies in the fact the MVC route registered is registered at `/sitemap.xml` rather than `*/sitemap.xml`. This is to prevent the same sitemap resolving multiple times per site, e.g. /sitemap.xml and /some-page/sitemap.xml, but obviously doesn't help in your situation.

I need to see how I could make a [catch-all route](https://docs.microsoft.com/en-us/previous-versions/cc668201(v=vs.140)?redirectedfrom=MSDN#handling-a-variable-number-of-segments-in-a-url-pattern) work in a safe way. I don't have any timeframes for this currently though.

Thanks,
Callum

**Comment by callumbwhyte** [comment]
Hey @daljitkaur9,

After a lot of investigation, supporting a catch-all route (that would be needed to support multiple sitemaps) is quite challenging in V8. This will be a lot easier to achieve in V9 of Umbraco / on .NET 5 as routing has been changed significantly there.

For now, I have provided an alternative solution for those who want to customise the sitemap routes.

As of v1.2.0, now out on all good package stores, you can configure this within a `Composer` like so:

```
composition.RegisterSitemap<T>(string path);
```

Cheers,
Callum
