### ISSUE TITLE
Routing does not work if hostname not set

### ISSUE THREAD

**Issue by AaronSadlerUK** [callumbwhyte/friendly-sitemap#12]
If the hostname is not set, the routing will not work and it will return the IIS 404 error rather than application 404 error.

The fact this also affects the friendly-robots plugin makes me think the issue lies in the routing extensions plugin

**Comment by callumbwhyte** [comment]
Hey @AaronSadlerUK,

Yep this was also raised previously. It's definitely an issue in [Routing Extensions](https://github.com/callumbwhyte/umbraco-routing-extensions) as that handles all the domain binding.

As for the 404, because the sitemap routes bypass the Umbraco pipeline entirely it isn't currently possible to use Umbraco's 404 handlers. Once the routing is fixed this is perhaps something we can look into however...

I'll add an issue to the [Routing Extensions](https://github.com/callumbwhyte/umbraco-routing-extensions) project for this to be investigated.

Cheers,
Callum

**Comment by AaronSadlerUK** [comment]
Sure, if I get time sometime this week I can pick this up, I just have a few other projects to finish first 👍

**Comment by callumbwhyte** [comment]
Thanks to @dampee this was fixed in the Routing Extensions package. Updating that dependency to the latest version will fix this issue!
