### ISSUE TITLE
sitemap contains only root url

### ISSUE THREAD

**Issue by elisa-rass** [callumbwhyte/friendly-sitemap#13]
Hello,

I have installed the package via Nuget, and have followed the steps described in this issue: #9  to make sure it was working, and now I have a sitemap :D but there is only the root url in it. I'm not sure if I'm missing something or if it is related to a bug... can you provide some assistance?

**Comment by qstoodleyrna** [comment]
I have just managed to get this working in 8.6.3 following the other thread about moving the DLL's and web.config and I too have the issue that it only shows the home page. This is all I am getting.

`<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9/">
<url>
<loc>https://www.siteurl.com/</loc>
<lastmod>2020-09-17</lastmod>
</url>
</urlset>`

Unfortunately this isn't going to be much help.

**Comment by callumbwhyte** [comment]
Hello @elisa-rass and @qstoodleyrna!

Thanks both for trying out Friendly Sitemap!

This issue isn't one I have come across personally, but I have a hunch what this might be... I was wondering if you could give me an idea of what your tree structure looks like in the CMS? A screenshot will do. If you're not comfortable posting here you can drop me an email: hey-at-callumwhyte-dot-com

Please can you also confirm the following:

- All of your content items have a template assigned
- None of your content types have a property with the alias `sitemapExclude `

Many thanks,
Callum

**Comment by qstoodleyrna** [comment]
Hi Callum, thanks for replying - I think this is the issue - I have two top level nodes so it is only picking up the first one. So for me it would be the ability to support multiple top level nodes and iterate each one.

**Comment by callumbwhyte** [comment]
Hey @qstoodleyrna,

Exactly, this was my theory.

Is it safe to assume you have a tree structure like below?

- Tree root
  - Home page
  - Some other page
    - Content page 1
    - Content page 2

If yes, do you have a hostname assigned to any of these nodes?

Thanks,
Callum

**Comment by qstoodleyrna** [comment]
Hi Callum, yes that is what I have and yes I do have a hostname assigned to the second node.

**Comment by callumbwhyte** [comment]
Hey @qstoodleyrna,

Just to clarify, which node in the above example is your hostname assigned to?

Thanks,
Callum

**Comment by qstoodleyrna** [comment]
Hi @callumbwhyte, they both have hostnames (different)

**Comment by callumbwhyte** [comment]
Hey @qstoodleyrna,

Thanks for confirming. This is a tricky one, due to the flexible nature of Umbraco and the varying approaches to structuring sites.

Friendly Sitemap assumes that each node in your tree with a unique hostname assigned is a standalone site and that node will have child nodes which should appear in the sitemap. e.g.

- **Tree root**
  - **Site 1** - _site1.com_
    - Some page
    - Some page
    - Some page
  - **Site 2** - _site2.com_
    - Some page
    - Some page
    - Some page

To achieve this Friendly Sitemap takes the node where the hostname is defined and calls Umbraco's `DescendantsOrSelf()` method.

If more than one root nodes have the hostnames for the same domain but different paths, these are treated as separate sites and will product multiple sitemaps. e.g.

- **Tree root**
  - **Homepage** - _example.com_
  - **Content** - _example.com/pages/_
    - Some page
    - Some page
    - Some page

I assume the latter is what you're trying to do?

To achieve this Friendly Sitemap would need to treat all nodes in the root of the tree as one site. This would need to be done in a way so as not to break option #1 above - I don't think this will be possible if still relying on hostnames. I believe fixing #12 (assuming first node is your site root when no hostname is defined) would mean we could assume all nodes in the tree are part of the same site and therefore appear in the sitemap.

Does this make sense and would this solve your issue?

Thanks,
Callum

**Comment by qstoodleyrna** [comment]
Hi @callumbwhyte, thanks for your help. My case is very much like your second example. I have tried re ordering the nodes as it is only the second node that I am interested in but that didn't work.

For me I have put your project in mine and modified the controller code to find the second node and all is working well for me now but that is a bit of a personalised hack.

Thanks
Quentin.

**Comment by callumbwhyte** [comment]
Hey @qstoodleyrna and @elisa-rass,

Just coming back to this now...

To support cases like yours where the tree is not hierarchical, the latest v1.2.0 version of Friendly Sitemap adds a `SitemapBuilderBase` class which you can override to tweak the output. This class has a method called `GetContentItems` which you can override to get the desired output.

Cheers.
Callum
